# Array creation

1.	Create a numpy array of size 10, filled with zeros

In [3]:
import numpy as np

arr = np.zeros(10)

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2.	Create a numpy array with values ranging from 10 to 49 and set its datatype to float

(Hint: Remember that you can set a specific dtype while defining an array for e.g. 
Arr1 =np.array([1,2,3,4,5]) #defines an int array by default
Arr2 =np.array([1,2,3,4,5], dtype = float) #specifying the dtype as an argument will create a float array). 


In [2]:
import numpy as np

arr = np.arange(10, 50) 
arr = arr.astype(float)

print(arr)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]



3.	Create a numpy matrix of 2*2 integers, filled with ones.


In [6]:
import numpy as np 
arr = np.ones((2,2) , dtype=int)
print(arr)

[[1 1]
 [1 1]]


4.	Create a numpy matrix of 3*2 float numbers, filled with ones.

In [8]:
import numpy as np
mat = np.ones((3,2) , dtype = float)
print (mat)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


5.	Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones. (#hint: search the function np.ones_like( ) )




In [9]:

import numpy as np

X = np.array([[1,2,3],[4,5,6]], dtype=int)

ones_arr = np.ones_like(X) 

print(ones_arr)

[[1 1 1]
 [1 1 1]]


6.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros. (hint: similar function as above exists for zeros as well)

In [10]:
import numpy as np

X = np.array([[1,2], [3,4]], dtype=int) 

zeros_mat = np.zeros_like(X)

print(zeros_mat)

[[0 0]
 [0 0]]


7.	Create a numpy matrix of 4*4 integers, filled with fives
.

In [11]:
import numpy as np

mat = np.full((4,4), 5, dtype=int) 

print(mat)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


8.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [14]:
import numpy as np

X = np.random.randint(0,10,(3,4)) 

seven_mat = np.full_like(X, 7)

print(seven_mat)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


9.	Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [15]:
import numpy as np

id_matrix = np.identity(3)

print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


10.	Create a numpy array, filled with 3 random integer values between 1 and 10.

In [17]:
import numpy as np

arr = np.random.randint(1,11,3)

print(arr)

[ 2  2 10]


11.	Create a 3*3*3 numpy matrix, filled with random float values.

In [18]:
import numpy as np

mat = np.random.random((3,3,3))

print(mat)

[[[0.20538225 0.66680579 0.15368297]
  [0.72952184 0.5341665  0.99927193]
  [0.35768913 0.34586511 0.50339589]]

 [[0.51018244 0.33750741 0.29371694]
  [0.78396857 0.51013822 0.07920091]
  [0.54827185 0.40914857 0.68234432]]

 [[0.78801102 0.81492276 0.34361651]
  [0.62924838 0.86327691 0.66948069]
  [0.71393383 0.00316436 0.36957922]]]


12.	Create a numpy array with numbers from 1 to 10

In [20]:
import numpy as np

arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


13.	Create a numpy array with the odd numbers between 1 to 10

In [21]:
import numpy as np

odds = np.arange(1, 11, 2)

print(odds)

[1 3 5 7 9]


14.	Create a numpy array with numbers from 1 to 10, in descending order.



In [22]:
import numpy as np

arr = np.arange(10, 0, -1)

print(arr)

[10  9  8  7  6  5  4  3  2  1]


15.	Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [24]:
import numpy as np

mat = np.arange(0,9).reshape(3,3)

print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Array indexing:

1.	Given the X numpy array, show its first element

X = np.array(['A','B','C','D','E'])



In [25]:
import numpy as np

X = np.array(['A','B','C','D','E'])

print(X[0])

A


2.	Given the X numpy array, show its last element

X = np.array(['A','B','C','D','E'])


In [27]:
import numpy as np 
X = np.array(['A','B','C','D','E'])
print(X[4])

E


3.	Given the X numpy array, show its first three elements

X = np.array(['A','B','C','D','E'])



In [29]:
import numpy as np 
X = np.array(['A','B','C','D','E'])
print(X[0:3])

['A' 'B' 'C']


4.	Given the X numpy array, show all middle elements

X = np.array(['A','B','C','D','E'])


In [30]:
import numpy as np 
X = np.array(['A','B','C','D','E'])
print(X[2])

C


5.	Given the X numpy array, show the elements in reverse position.

X = np.array(['A','B','C','D','E'])


In [31]:
import numpy as np

X = np.array(['A','B','C','D','E'])

print(X[::-1])

['E' 'D' 'C' 'B' 'A']


6.	Given the X numpy array, show the elements in an odd position.

X = np.array(['A','B','C','D','E'])


In [32]:
import numpy as np

X = np.array(['A','B','C','D','E'])

print(X[0:5:2])

['A' 'C' 'E']


7.	Given the X numpy matrix, show the first row’s elements.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [33]:
import numpy as np

X = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8],
              [9, 10, 11, 12], 
              [13, 14, 15, 16]])

print(X[0,:])

[1 2 3 4]


8.	Given the X numpy matrix, show the last row elements.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])



In [35]:
import numpy as np

X = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8],
              [9, 10, 11, 12], 
              [13, 14, 15, 16]])

print(X[-1,:])

[13 14 15 16]


9.	Given the X numpy matrix, show the first element on first row

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])


In [36]:
import numpy as np

X = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

print(X[0,0])

1



10.	Given the X numpy matrix, show the last element on last row.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [39]:
import numpy as np

X = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

print(X[-1,-1])

16


11.	Given the X numpy matrix, show the first two elements on the first two rows.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])



In [40]:
import numpy as np

X = np.array([[1, 2, 3, 4],  
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

print(X[:2, :2])

[[1 2]
 [5 6]]


12.	Given the X numpy matrix, show the last two elements on the last two rows

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [41]:
import numpy as np

X = np.array([[1, 2, 3, 4],  
              [5, 6, 7, 8],
              [9, 10, 11, 12], 
              [13, 14, 15, 16]])

print(X[-2:, -2:])

[[11 12]
 [15 16]]


# Array manipulation

1.	Convert the given integer numpy array to float (you need to google the function that will help you do this)

X = [-5, -3, 0, 10, 40]


In [42]:
import numpy as np

X = np.array([-5, -3, 0, 10, 40])
X = X.astype(float)

print(X) 
print(X.dtype)

[-5. -3.  0. 10. 40.]
float64


2.	Reverse the given numpy array (first element becomes last) through indexing

X = [-5, -3, 0, 10, 40]


In [43]:
import numpy as np

X = np.array([-5, -3, 0, 10, 40])

X = X[::-1]

print(X)

[40 10  0 -3 -5]


3.	Given the X numpy array, set the fifth element equal to 1

X = np.zeros(10)


In [44]:
import numpy as np

X = np.zeros(10) 

X[4] = 1

print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4.	Given the X numpy matrix, change the last row with all 1

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [45]:
import numpy as np

X = np.array([[1, 2, 3, 4],  
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

X[-1,:] = np.ones(4) 

print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


5.	Given the X numpy matrix, add 5 to every element

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [46]:
import numpy as np

X = np.array([[1, 2, 3, 4],  
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

X += 5

print(X)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
